import React, { useState } from 'react';
import { useNavigate, NavLink, Link } from 'react-router-dom';
import logo from '../assets/logo2.png';
import logoKiri from '../assets/logo3.png';
import { motion } from 'framer-motion';

const Menu = () => {
  const navigate = useNavigate();
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedItem, setSelectedItem] = useState(null);

  // Data menu langsung
  const rekomendasiMenu = [
    { "nama": "Abon", "kalori": 280 },
    { "nama": "Agar-agar", "kalori": 0 },
    { "nama": "Akar tonjong", "kalori": 45 },
    { "nama": "Aletoge", "kalori": 37 },
    { "nama": "Alpukat", "kalori": 85 },
    { "nama": "Andaliman", "kalori": 99 },
    { "nama": "Andewi", "kalori": 25 },
    { "nama": "Anggur", "kalori": 30 },
    { "nama": "Anyang sayur", "kalori": 126 },
    { "nama": "Apel", "kalori": 58 },
    { "nama": "Apel malang", "kalori": 57 },
    { "nama": "Arbei", "kalori": 37 },
    { "nama": "Asinan Bogor", "kalori": 98 },
    { "nama": "Sayap Crispy", "kalori": 297 },
    { "nama": "Ampela goreng", "kalori": 270 },
    { "nama": "Dada Crispy", "kalori": 298 },
    { "nama": "Paha Crispy", "kalori": 286 },
    { "nama": "Ayam taliwang", "kalori": 264 },
    { "nama": "Usus goreng", "kalori": 473 },
    { "nama": "Babat", "kalori": 113 },
    { "nama": "Bacang", "kalori": 102.9 },
    { "nama": "Bakpia kue", "kalori": 272 },
    { "nama": "Bakso", "kalori": 76 },
    { "nama": "Bakwan", "kalori": 280 },
    { "nama": "Kue Bantal", "kalori": 190 },
    { "nama": "Barongko", "kalori": 159 },
    { "nama": "Bawang Bombay", "kalori": 45 },
    { "nama": "Bawang Merah", "kalori": 39 },
    { "nama": "Bawang Putih", "kalori": 95 },
    { "nama": "Bayam kukus", "kalori": 30 },
    { "nama": "Bayam Merah", "kalori": 51 },
    { "nama": "Bayam rebus", "kalori": 23 },
    { "nama": "Bayam segar", "kalori": 36 },
    { "nama": "Bayam tumis", "kalori": 102 },
    { "nama": "Bayam tumis santan", "kalori": 48 },
    { "nama": "Bebek goreng", "kalori": 300 },
    { "nama": "Beberuk", "kalori": 65 },
    { "nama": "Beef burger", "kalori": 258 },
    { "nama": "Beef teriyaki", "kalori": 151 },
    { "nama": "Beef yakiniku", "kalori": 132 },
    { "nama": "Bekasam", "kalori": 116 },
    { "nama": "Bekasang", "kalori": 78 },
    { "nama": "Belimbing", "kalori": 36 },
    { "nama": "Belitung talas kukus", "kalori": 145 },
    { "nama": "Belut goreng", "kalori": 417 },
    { "nama": "Bengkuang", "kalori": 55 },
    { "nama": "Bentul (Komba) talas", "kalori": 98 },
    { "nama": "Bentul talas kukus", "kalori": 71 },
    { "nama": "Beras Ketan Hitam kukus", "kalori": 181 },
    { "nama": "Beras Ketan Hitam tape", "kalori": 166 },
    { "nama": "Beras Ketan Putih kukus", "kalori": 163 },
    { "nama": "Beras Ketan Putih tape", "kalori": 172 },
    { "nama": "Betok wadi", "kalori": 145 },
    { "nama": "Bihun Goreng", "kalori": 154 },
    { "nama": "Bihun goreng instan", "kalori": 381 },
    { "nama": "Bika Ambon", "kalori": 225.7 },
    { "nama": "Biskuit", "kalori": 458 },
    { "nama": "Bit", "kalori": 42 },
    { "nama": "Biwah segar", "kalori": 51 },
    { "nama": "Bongkrek (tempe bungkil)", "kalori": 119 },
    { "nama": "Botok lamtoro", "kalori": 186 },
    { "nama": "Brem", "kalori": 249 },
    { "nama": "Brondong", "kalori": 400 },
    { "nama": "Brongkos", "kalori": 141 },
    { "nama": "Buah Atung", "kalori": 23 },
    { "nama": "Buah kelenting", "kalori": 110 },
    { "nama": "Buah kelor", "kalori": 38 },
    { "nama": "Buah Naga Merah", "kalori": 71 },
    { "nama": "Buah Naga Putih", "kalori": 56 },
    { "nama": "Buah negri segar", "kalori": 55 },
    { "nama": "Bubur", "kalori": 60 },
    { "nama": "Bubur sagu", "kalori": 167 },
    { "nama": "Bubur Manado", "kalori": 156 },
    { "nama": "Bulgogi", "kalori": 72 },
    { "nama": "Buncis rebus", "kalori": 30 },
    { "nama": "Bunga turi segar", "kalori": 42 },
    { "nama": "Bungkil Biji Karet", "kalori": 333 },
    { "nama": "Bungkil Kacang Tanah", "kalori": 336 },
    { "nama": "Bungkil Kelapa", "kalori": 368 },
    { "nama": "Buntil", "kalori": 106 },
    { "nama": "Buntil daun talas", "kalori": 141 },
    { "nama": "Buras", "kalori": 125.7 },
    { "nama": "Cabai merah kering", "kalori": 367 },
    { "nama": "Cabai merah segar", "kalori": 36 },
    { "nama": "Cabai rawit segar", "kalori": 120 },
    { "nama": "Caisin segar", "kalori": 20 },
    { "nama": "Cakalang asap", "kalori": 155 },
    { "nama": "Cake tape", "kalori": 323 },
    { "nama": "Cap cai sayur", "kalori": 97 },
    { "nama": "Carica papaya segar", "kalori": 24 },
    { "nama": "Cassava stick", "kalori": 460 },
    { "nama": "Cempedak", "kalori": 116 },
    { "nama": "Ceriping getuk singkong", "kalori": 462 },
    { "nama": "Chicken teriyaki", "kalori": 168 },
    { "nama": "Chikiniku", "kalori": 143 },
    { "nama": "Coklat bubuk", "kalori": 311 },
    { "nama": "Coklat Manis", "kalori": 472 },
    { "nama": "Coklat Pahit", "kalori": 504 },
    { "nama": "Coklat Susu", "kalori": 381 },
    { "nama": "Combro", "kalori": 210 },
    { "nama": "Corned Beef", "kalori": 241 },
    { "nama": "Coto mangkasara kuda", "kalori": 96 },
    { "nama": "Coto mangkasara sapi", "kalori": 84 },
    { "nama": "Cue Selar Kuning", "kalori": 145 },
    { "nama": "Cuka", "kalori": 12 },
    { "nama": "Cumi-cumi goreng", "kalori": 265 },
    { "nama": "Daging Asap", "kalori": 191 },
    { "nama": "Daging Domba", "kalori": 206 },
    { "nama": "Daging Kambing", "kalori": 154 },
    { "nama": "Daging Kerbau", "kalori": 84 },
    { "nama": "Daging Kuda", "kalori": 118 },
    { "nama": "Daging Sapi", "kalori": 207 },
    { "nama": "Daun Bawang", "kalori": 29 },
    { "nama": "Daun katuk rebus", "kalori": 53 },
    { "nama": "Daun Kelor rebus", "kalori": 61 },
    { "nama": "Daun Kemangi", "kalori": 46 },
    { "nama": "Daun kol sawi segar", "kalori": 22 },
    { "nama": "Daun Koro", "kalori": 23 },
    { "nama": "Daun kubis segar", "kalori": 51 },
    { "nama": "Daun Kumak", "kalori": 14 },
    { "nama": "Daun Labu Siam", "kalori": 60 },
    { "nama": "Daun Labu Waluh", "kalori": 30 },
    { "nama": "Daun lamtoro segar", "kalori": 87 },
    { "nama": "Daun leilem segar", "kalori": 76 },
    { "nama": "Daun Leunca", "kalori": 45 },
    { "nama": "Daun Lobak", "kalori": 30 },
    { "nama": "Daun Lompong Tales", "kalori": 40 },
    { "nama": "Daun Mangkokan", "kalori": 54 },
    { "nama": "Daun Oyong", "kalori": 22 },
    { "nama": "Daun Pete Cina", "kalori": 128 },
    { "nama": "Daun Poh-pohan", "kalori": 37 },
    { "nama": "Daun Singkong lodeh", "kalori": 55 },
    { "nama": "Daun Singkong rebus", "kalori": 31 },
    { "nama": "Daun Ubi Jalar kukus", "kalori": 56 },
    { "nama": "Deblo", "kalori": 260 },
    { "nama": "Dendeng belut goreng", "kalori": 382 },
    { "nama": "Dendeng Daging Sapi", "kalori": 433 },
    { "nama": "Dendeng mujahir goreng", "kalori": 598 },
    { "nama": "Dodol", "kalori": 395 },
    { "nama": "Dodol bali", "kalori": 298 },
    { "nama": "Dodol banjarmasin", "kalori": 368 },
    { "nama": "Dodol galamai", "kalori": 348 },
    { "nama": "Dodol kedondong", "kalori": 331 },
    { "nama": "Dodol manado", "kalori": 373 },
    { "nama": "Dodonkol", "kalori": 17.5 },
    { "nama": "Duku", "kalori": 63 },
    { "nama": "Durian", "kalori": 134 },
    { "nama": "Duwet", "kalori": 80 },
    { "nama": "Empal Goreng", "kalori": 590 },
    { "nama": "Emping", "kalori": 345 },
    { "nama": "Emping beras", "kalori": 403 },
    { "nama": "Emping komak", "kalori": 355 },
    { "nama": "Encung asam", "kalori": 122 },
    { "nama": "Es krim", "kalori": 210 },
    { "nama": "Es Krim (Coconut milk)", "kalori": 156.7 },
    { "nama": "Es Mambo", "kalori": 152 },
    { "nama": "Es Sirup", "kalori": 44.8 },
    { "nama": "Fillet o-fish", "kalori": 270 },
    { "nama": "Gadung kering", "kalori": 322 },
    { "nama": "Gado-gado", "kalori": 137 },
    { "nama": "Gadung kukus", "kalori": 88 },
    { "nama": "Gadung ubi kukus", "kalori": 88 },
    { "nama": "Gambas lodeh", "kalori": 13 },
    { "nama": "Gandaria", "kalori": 68 },
    { "nama": "Ganyong kukus", "kalori": 100 },
    { "nama": "Ganyong rebus", "kalori": 100 },
    { "nama": "Ganyong segar", "kalori": 77 },
    { "nama": "Gaplek", "kalori": 338 },
    { "nama": "Gatep segar", "kalori": 191 },
    { "nama": "Gatot", "kalori": 347 },
    { "nama": "Geblek", "kalori": 195 },
    { "nama": "Gelatine", "kalori": 389 },
    { "nama": "Gembili", "kalori": 95 },
    { "nama": "Gembili ubi segar", "kalori": 131 },
    { "nama": "Gemblong", "kalori": 274 },
    { "nama": "Gendar goreng", "kalori": 407 },
    { "nama": "Genjer segar", "kalori": 35 },
    { "nama": "Geplak", "kalori": 350 },
    { "nama": "Geplak jahe", "kalori": 462 },
    { "nama": "Gete kuah asam", "kalori": 75 },
    { "nama": "Getuk goreng", "kalori": 360 },
    { "nama": "Getuk Lindri", "kalori": 171.4 },
    { "nama": "Getuk pisang", "kalori": 144 },
    { "nama": "Getuk singkong", "kalori": 204 },
    { "nama": "Gudeg", "kalori": 53 },
    { "nama": "Gudeg sayur", "kalori": 160 },
    { "nama": "Gula Aren", "kalori": 368 },
    { "nama": "Gula Kelapa", "kalori": 386 },
    { "nama": "Gula putih", "kalori": 394 },
    { "nama": "Gulai asam keueung", "kalori": 52 },
    { "nama": "Gulai ikan", "kalori": 106 },
    { "nama": "Gulai ikan paya", "kalori": 148 },
    { "nama": "Gulai kambing", "kalori": 126 },
    { "nama": "Gulai keumamah", "kalori": 110 },
    { "nama": "Gulai pakis", "kalori": 143 },
    { "nama": "Gulai pliek", "kalori": 176 },
    { "nama": "Gulai tiram", "kalori": 132 },
    { "nama": "Gurame asem manis", "kalori": 192 },
    { "nama": "Gurandil", "kalori": 218 },
    { "nama": "Ham", "kalori": 389 },
    { "nama": "Hangop", "kalori": 65 },
    { "nama": "Havermout", "kalori": 390 },
    { "nama": "Ubi hutan", "kalori": 127 },
    { "nama": "Ikan asar merah", "kalori": 146 },
    { "nama": "Ikan Asin bilis goreng", "kalori": 380 },
    { "nama": "Ikan Asin gabus goreng", "kalori": 456 },
    { "nama": "Ikan Asin japuh goreng", "kalori": 348 },
    { "nama": "Ikan Asin kering", "kalori": 193 },
    { "nama": "Ikan Asin pari goreng", "kalori": 430 },
    { "nama": "Ikan Asin pepetek goreng", "kalori": 652 },
    { "nama": "Ikan Asin sirinding goreng", "kalori": 319 },
    { "nama": "Ikan Asin teri goreng", "kalori": 430 },
    { "nama": "Ikan Bader (Tawes)", "kalori": 198 },
    { "nama": "Ikan bambangan segar", "kalori": 112 },
    { "nama": "Ikan Bandeng", "kalori": 129 },
    { "nama": "Ikan bandeng presto", "kalori": 296 },
    { "nama": "Ikan baung bakar", "kalori": 144 },
    { "nama": "Ikan baung segar", "kalori": 123 },
    { "nama": "Ikan Bawal", "kalori": 96 },
    { "nama": "Ikan Bekasang", "kalori": 138 },
    { "nama": "Ikan Belida bakar", "kalori": 128 },
    { "nama": "Ikan Belut Segar goreng", "kalori": 417 },
    { "nama": "Ikan Ekor Kuning", "kalori": 109 },
    { "nama": "Ikan Gabus kering", "kalori": 292 },
    { "nama": "Ikan Gabus", "kalori": 74 },
    { "nama": "Ikan gete goreng", "kalori": 267 },
    { "nama": "Ikan hiu kering", "kalori": 298 },
    { "nama": "Ikan kayu kering", "kalori": 302 },
    { "nama": "Ikan Kembung", "kalori": 103 },
    { "nama": "Ikan Lele goreng", "kalori": 252 },
    { "nama": "Ikan Lemuru", "kalori": 112 },
    { "nama": "Ikan Mas goreng", "kalori": 188 },
    { "nama": "Ikan Mas pepes", "kalori": 209 },
    { "nama": "Ikan Mujair goreng", "kalori": 416 },
    { "nama": "Ikan Mujair pepes", "kalori": 121 },
    { "nama": "Ikan Papuyu bakar", "kalori": 152 },
    { "nama": "Ikan Patin bakar", "kalori": 144 },
    { "nama": "Ikan sanggang masakan", "kalori": 240 },
    { "nama": "Ikan Teri kering", "kalori": 170 },
    { "nama": "Ikan Teri Kering tawar", "kalori": 331 },
    { "nama": "Ikan Teri Nasi kering", "kalori": 144 },
    { "nama": "Jagung grontol", "kalori": 156 },
    { "nama": "Jagung Kuning giling", "kalori": 361 },
    { "nama": "Jagung Kuning muda", "kalori": 129 },
    { "nama": "Jagung Kuning pipil baru", "kalori": 307 },
    { "nama": "Jagung kuning pipil kering", "kalori": 366 },
    { "nama": "Jagung Kuning pipil lama", "kalori": 355 },
    { "nama": "Jagung kuning pipil rebus", "kalori": 154 },
    { "nama": "Jagung Kuning segar", "kalori": 140 },
    { "nama": "Jagung kuning tepung", "kalori": 355 },
    { "nama": "Jagung muda", "kalori": 35 },
    { "nama": "Jagung muda kuning", "kalori": 147 },
    { "nama": "Jagung muda rebus", "kalori": 142 },
    { "nama": "Jagung Rebus", "kalori": 175 },
    { "nama": "Jagung tumis", "kalori": 148.9 },
    { "nama": "Jagung titi", "kalori": 374 },
    { "nama": "Jahe", "kalori": 51 },
    { "nama": "Jali", "kalori": 289 },
    { "nama": "Jam selai", "kalori": 239 },
    { "nama": "Jambal goreng", "kalori": 286 },
    { "nama": "Jambu Air", "kalori": 46 },
    { "nama": "Jambu Biji", "kalori": 49 },
    { "nama": "Jambu biji putih tidak berbiji", "kalori": 61 },
    { "nama": "Jambu Bol", "kalori": 56 },
    { "nama": "Jambu Monyet buah", "kalori": 64 },
    { "nama": "Jampang huma mentah", "kalori": 350 },
    { "nama": "Jamur Coklat", "kalori": 45 },
    { "nama": "Jamur encik", "kalori": 296 },
    { "nama": "Jamur kuping kering", "kalori": 294 },
    { "nama": "Jamur kuping segar", "kalori": 21 },
    { "nama": "Jamur merang segar", "kalori": 30 },
    { "nama": "Jamur Putih", "kalori": 48 },
    { "nama": "Jamur sagu", "kalori": 48 },
    { "nama": "Jamur tiram segar", "kalori": 30 },
    { "nama": "Jeruk Bali", "kalori": 48 },
    { "nama": "Jeruk banjar", "kalori": 61 },
    { "nama": "Jeruk Garut", "kalori": 44 },
    { "nama": "Jeruk Kalamansi", "kalori": 39 },
    { "nama": "Jeruk Manis", "kalori": 45 },
    { "nama": "Jeruk Nipis", "kalori": 37 },
    { "nama": "Jeruk ragi", "kalori": 49 },
    { "nama": "Jotang", "kalori": 32 },
    { "nama": "Kabuto", "kalori": 250 },
    { "nama": "Kacang Andong", "kalori": 356 },
    { "nama": "Kacang Arab", "kalori": 330 },
    { "nama": "Kacang atom", "kalori": 533 },
    { "nama": "Kacang babi kering", "kalori": 341 },
    { "nama": "Kacang belimbing kering", "kalori": 400 },
    { "nama": "Kacang Belimbing rebus", "kalori": 204 },
    { "nama": "Kacang Belimbing tempe", "kalori": 212 },
    { "nama": "Kacang beracun segar", "kalori": 118 },
    { "nama": "Kacang Bogor goreng", "kalori": 479 },
    { "nama": "Kacang bogor kering", "kalori": 370 },
    { "nama": "Kacang Bogor rebus", "kalori": 161 },
    { "nama": "Kacang bogor segar", "kalori": 165 },
    { "nama": "Kacang Endel biji", "kalori": 331 },
    { "nama": "Kacang ercis segar", "kalori": 129 },
    { "nama": "kacang galing segar", "kalori": 336 },
    { "nama": "Kacang goyang", "kalori": 516 },
    { "nama": "Kacang Gude biji", "kalori": 336 },
    { "nama": "Kacang gude biji kering", "kalori": 316 },
    { "nama": "Kacang Gude biji muda", "kalori": 114 },
    { "nama": "Kacang Gude muda", "kalori": 123 },
    { "nama": "Kacang gude rebus", "kalori": 147 },
    { "nama": "Kacang hijau kering", "kalori": 323 },
    { "nama": "kacang hijau rebus", "kalori": 109 },
    { "nama": "Kacang hitam kering", "kalori": 346 },
    { "nama": "Kacang Ijo", "kalori": 345 },
    { "nama": "Kacang Kapri Goreng", "kalori": 445 },
    { "nama": "Kacang Kapri muda", "kalori": 98 },
    { "nama": "Kacang Kedelai basah", "kalori": 286 },
    { "nama": "Kacang kedelai goreng", "kalori": 521 },
    { "nama": "Kacang kedelai kering", "kalori": 381 },
    { "nama": "Kacang Kedelai kukus", "kalori": 75 },
    { "nama": "Kacang kedelai rebus", "kalori": 189 },
    { "nama": "Kacang kedelai", "kalori": 286 },
    { "nama": "Kacang komak", "kalori": 327 },
    { "nama": "Kacang kuning kering", "kalori": 355 },
    { "nama": "Kacang lebui", "kalori": 346 },
    { "nama": "Kacang mekah polong", "kalori": 22 },
    { "nama": "Kacang mentega kering", "kalori": 344 },
    { "nama": "Kacang Merah", "kalori": 336 },
    { "nama": "Kacang merah /banda kering", "kalori": 350 },
    { "nama": "Kacang merah kering", "kalori": 314 },
    { "nama": "Kacang Merah kering rebus", "kalori": 158 },
    { "nama": "Kacang merah", "kalori": 171 },
    { "nama": "Kacang Merah rebus", "kalori": 144 },
    { "nama": "Kacang merah tua kering", "kalori": 280 },
    { "nama": "Kacang mete goreng", "kalori": 629 },
    { "nama": "Kacang mete segar", "kalori": 616 },
    { "nama": "Kacang negara", "kalori": 480 },
    { "nama": "Kacang Panjang", "kalori": 44 },
    { "nama": "Kacang Panjang biji", "kalori": 357 },
    { "nama": "Kacang Panjang kukus", "kalori": 39 },
    { "nama": "Kacang Panjang tumis", "kalori": 150 },
    { "nama": "Kacang ranti polong", "kalori": 37 },
    { "nama": "Kacang sukro", "kalori": 484 },
    { "nama": "Kacang Sukro Putih", "kalori": 488 },
    { "nama": "Kacang Tanah atom", "kalori": 535 },
    { "nama": "Kacang tanah goreng", "kalori": 564 },
    { "nama": "Kacang Tanah kacang sari", "kalori": 561 },
    { "nama": "Kacang tanah kering", "kalori": 525 },
    { "nama": "Kacang Tanah Rebus", "kalori": 385 },
    { "nama": "Kacang Tanah rebus berkulit", "kalori": 360 },
    { "nama": "Kacang Tanah rempeyek", "kalori": 513 },
    { "nama": "Kacang Tanah sangan berselaput", "kalori": 569 },
    { "nama": "Kacang tanah sangan tanpa selaput", "kalori": 559 },
    { "nama": "Kacang tanah sari", "kalori": 561 },
    { "nama": "Kacang Telur", "kalori": 748 },
    { "nama": "Kacang tolo kering", "kalori": 331 },
    { "nama": "Kacang tolo rebus", "kalori": 138 },
    { "nama": "Kacang Tunggak", "kalori": 342 },
    { "nama": "Kacang Tunggak rebus", "kalori": 138 },
    { "nama": "Kacang Tunggak rempeyek", "kalori": 451 },
    { "nama": "Kacang tunis kering", "kalori": 351 },
    { "nama": "Kacang uci kering", "kalori": 358 },
    { "nama": "Kacang urei kering", "kalori": 354 },
    { "nama": "Kadada katembe", "kalori": 110 },
    { "nama": "Kaholeo", "kalori": 413 },
    { "nama": "Kakap", "kalori": 92 },
    { "nama": "Kalakai", "kalori": 66 },
    { "nama": "Kalio jeroan", "kalori": 163 },
    { "nama": "Kalio kikil (tunjang)", "kalori": 122 },
    { "nama": "Kalio otak masakan", "kalori": 157 },
    { "nama": "Kalio telur masakan", "kalori": 193 },
    { "nama": "Kalio Udang", "kalori": 158 },
    { "nama": "Kaliandra", "kalori": 73 },
    { "nama": "Kampung", "kalori": 185 },
    { "nama": "Kampung Batak", "kalori": 125 },
    { "nama": "Kampung Roti", "kalori": 160 },
    { "nama": "Kampung Tandu", "kalori": 143 },
    { "nama": "Kanji", "kalori": 380 },
    { "nama": "Kanji hitam", "kalori": 102 },
    { "nama": "Kanji jagung", "kalori": 117 },
    { "nama": "Kanji Jagung manis", "kalori": 85 },
    { "nama": "Kanji Kacang Hijau", "kalori": 72 },
    { "nama": "Kecipir biji", "kalori": 405 },
    { "nama": "Kecipir buah muda", "kalori": 35 },
    { "nama": "Kecipir muda", "kalori": 32 },
    { "nama": "Kecombrang", "kalori": 34 },
    { "nama": "Kedondong", "kalori": 47 },
    { "nama": "Keju", "kalori": 326 },
    { "nama": "Keju Kacang Tanah", "kalori": 590 },
    { "nama": "Kelapa hutan kering", "kalori": 623 },
    { "nama": "Kelapa Muda air", "kalori": 17 },
    { "nama": "Kelapa Muda daging", "kalori": 68 },
    { "nama": "Kelapa Setengah Tua daging", "kalori": 180 },
    { "nama": "Kelapa Tua daging", "kalori": 359 },
    { "nama": "Kelepon", "kalori": 214 },
    { "nama": "Kelewih", "kalori": 111 },
    { "nama": "Kembang tahu", "kalori": 380 },
    { "nama": "Kembang Turi", "kalori": 44 },
    { "nama": "Kemiri", "kalori": 636 },
    { "nama": "Kenari", "kalori": 657 },
    { "nama": "Kenari banda kering", "kalori": 616 },
    { "nama": "Kentang", "kalori": 83 },
    { "nama": "Kentang Hitam", "kalori": 142 },
    { "nama": "Keong", "kalori": 64 },
    { "nama": "Kepala Susu (Krim)", "kalori": 204 },
    { "nama": "Kepiting", "kalori": 151 },
    { "nama": "Kerang", "kalori": 59 },
    { "nama": "Kerang asap mentah", "kalori": 393 },
    { "nama": "Keripik bayam", "kalori": 586 },
    { "nama": "Keripik gadung", "kalori": 446 },
    { "nama": "Keripik kentang", "kalori": 448 },
    { "nama": "Keripik lampung", "kalori": 485 },
    { "nama": "Keripik oncom", "kalori": 598 },
    { "nama": "Keripik singkong", "kalori": 478 },
    { "nama": "Keripik singkong berbumbu", "kalori": 481 },
    { "nama": "Keripik tempe", "kalori": 581 },
    { "nama": "Keripik tempe abadi murni", "kalori": 542 },
    { "nama": "Keripik tempe abadi sedang", "kalori": 510 },
    { "nama": "Keripik tempe abadi telur", "kalori": 529 },
    { "nama": "Keripik ubi", "kalori": 486 },
    { "nama": "Kerokot", "kalori": 26 },
    { "nama": "Kerupuk Aci", "kalori": 350 },
    { "nama": "Kerupuk cumi goreng", "kalori": 444 },
    { "nama": "Kerupuk Ikan berpati", "kalori": 342 },
    { "nama": "Kerupuk kemplang", "kalori": 325 },
    { "nama": "Kerupuk kemplang goreng", "kalori": 504 },
    { "nama": "Kerupuk kemplang panggang", "kalori": 356 },
    { "nama": "Kerupuk Kulit kerbau", "kalori": 422 },
    { "nama": "Kerupuk Melinjo mentah", "kalori": 345 },
    { "nama": "Kerupuk Melinjo tebal goreng asin", "kalori": 431 },
    { "nama": "Kerupuk Melinjo tebal goreng manis", "kalori": 439 },
    { "nama": "Kerupuk Melinjo tipis goreng", "kalori": 485 },
    { "nama": "Kerupuk mie kuning goreng", "kalori": 476 },
    { "nama": "Kerupuk Sayong", "kalori": 46.7 },
    { "nama": "Kerupuk Udang", "kalori": 340 },
    { "nama": "Kerupuk Udang berpati", "kalori": 359 },
    { "nama": "Kerupuk udang goreng", "kalori": 477 },
    { "nama": "Kerupuk urat", "kalori": 588 },
    { "nama": "Kesemek", "kalori": 78 },
    { "nama": "Ketan hitam matang", "kalori": 181 },
    { "nama": "Ketan putih matang", "kalori": 163 },
    { "nama": "Ketapang", "kalori": 340 },
    { "nama": "Ketela Pohon Kuning", "kalori": 157 },
    { "nama": "Ketela singkong", "kalori": 154 },
    { "nama": "Ketela pohon kukus", "kalori": 153 },
    { "nama": "Ketimun", "kalori": 12 },
    { "nama": "Ketimun madura", "kalori": 9 },
    { "nama": "Ketoprak", "kalori": 153 },
    { "nama": "Ketumbar", "kalori": 404 },
    { "nama": "Ketupat ketan", "kalori": 212 },
    { "nama": "Ketupat Tahu", "kalori": 109.6 },
    { "nama": "Kokosan", "kalori": 86 },
    { "nama": "Komak polong", "kalori": 99 },
    { "nama": "Kool Kembang", "kalori": 25 },
    { "nama": "Kool Merah kool putih", "kalori": 24 },
    { "nama": "Kopi bagian yang larut", "kalori": 352 },
    { "nama": "Kopi bubuk instant", "kalori": 129 },
    { "nama": "Koro andong kering", "kalori": 356 },
    { "nama": "Koro Benguk biji", "kalori": 332 },
    { "nama": "Koro Benguk tempe", "kalori": 141 },
    { "nama": "Koro Kerupuk biji", "kalori": 125 },
    { "nama": "Koro Loke biji", "kalori": 33 },
    { "nama": "Koro Roway biji", "kalori": 344 },
    { "nama": "Koro Wedus biji", "kalori": 338 },
    { "nama": "Koro Wedus buah muda", "kalori": 38 },
    { "nama": "Koro wedus polong", "kalori": 46 },
    { "nama": "Kotiu hinela tawang nggole", "kalori": 46 },
    { "nama": "Koya", "kalori": 366 },
    { "nama": "Koya mirasa", "kalori": 370 },
    { "nama": "Kranji segar", "kalori": 315 },
    { "nama": "Kripik Tempe Goreng", "kalori": 542 },
    { "nama": "Krokot", "kalori": 21 },
    { "nama": "Kucai", "kalori": 45 },
    { "nama": "Kucai Muda (Lokio)", "kalori": 42 },
    { "nama": "Kue ali", "kalori": 440 },
    { "nama": "Kue Apem", "kalori": 186.7 },
    { "nama": "Kue bangket", "kalori": 338 },
    { "nama": "Kue Bugis", "kalori": 240 },
    { "nama": "Kue jahe", "kalori": 425 },
    { "nama": "Kue kelapa", "kalori": 591 },
    { "nama": "Kue Koya", "kalori": 366 },
    { "nama": "Kue lumpur", "kalori": 291 },
    { "nama": "Kue mangkok", "kalori": 182 },
    { "nama": "Kue Pacar Cina", "kalori": 126.7 },
    { "nama": "Kue Pia", "kalori": 296 },
    { "nama": "Kue putu cangkir", "kalori": 304 },
    { "nama": "Kue putu singkong", "kalori": 217 },
    { "nama": "Kue Satu", "kalori": 393.3 },
    { "nama": "Kue Semprong", "kalori": 380 },
    { "nama": "Kue sus", "kalori": 221 },
    { "nama": "Kue Talam", "kalori": 180 },
    { "nama": "Kue Tambang", "kalori": 512 },
    { "nama": "Kue thipan", "kalori": 247 },
    { "nama": "Kwaci", "kalori": 515 },
    { "nama": "Kwark (Quark)", "kalori": 242 },
    { "nama": "Labu Air", "kalori": 17 },
    { "nama": "Labu kuning segar", "kalori": 51 },
    { "nama": "Labu Siam", "kalori": 26 },
    { "nama": "Labu waluh segar", "kalori": 32 },
    { "nama": "Laksa", "kalori": 166.3 },
    { "nama": "Lamtoro (pete cina) biji muda", "kalori": 85 },
    { "nama": "Lamtoro biji tua", "kalori": 148 },
    { "nama": "Lamtoro tempe", "kalori": 142 },
    { "nama": "Lamtoro var. gung tanpa kulit", "kalori": 367 },
    { "nama": "Lamtoro var. lokal dengan kulit", "kalori": 336 },
    { "nama": "Langsat", "kalori": 56 },
    { "nama": "Lantar segar", "kalori": 34 },
    { "nama": "Lanting getuk", "kalori": 422 },
    { "nama": "Lapis legit", "kalori": 389 },
    { "nama": "Lawar babi masakan", "kalori": 174 },
    { "nama": "Lawar penyu masakan", "kalori": 141 },
    { "nama": "Lawara jangang masakan", "kalori": 159 },
    { "nama": "Lawara penjah masakan", "kalori": 207 },
    { "nama": "Ledre pisang", "kalori": 405 },
    { "nama": "Lema/ Rebung asam", "kalori": 15 },
    { "nama": "Lemak Babi", "kalori": 902 },
    { "nama": "Lemak Babi (Bacon)", "kalori": 630 },
    { "nama": "Lemak ikan", "kalori": 372 },
    { "nama": "Lemak Kerbau", "kalori": 818 },
    { "nama": "Lemon segar", "kalori": 34 },
    { "nama": "Lemon Squasih", "kalori": 36 },
    { "nama": "Lemonade", "kalori": 30 },
    { "nama": "Lemper", "kalori": 221.3 },
    { "nama": "Lempog durian", "kalori": 320 },
    { "nama": "Lepok/Ubi rumput", "kalori": 181 },
    { "nama": "Leunca buah", "kalori": 33 },
    { "nama": "Leupeut Ketan", "kalori": 240 },
    { "nama": "Leverwost (sosis hati)", "kalori": 387 },
    { "nama": "Lilin bungkus gedi", "kalori": 79 },
    { "nama": "Lobak", "kalori": 19 },
    { "nama": "Lokan segar", "kalori": 217 },
    { "nama": "Lontar segar", "kalori": 27 },
    { "nama": "Lopis", "kalori": 163.3 },
    { "nama": "Lumai/Leunca segar", "kalori": 38 },
    { "nama": "Lupis ketan", "kalori": 164 },
    { "nama": "Madu", "kalori": 294 },
    { "nama": "Makaroni", "kalori": 363 },
    { "nama": "Mangga benggala segar", "kalori": 63 },
    { "nama": "Mangga Gedong", "kalori": 44 },
    { "nama": "Mangga Golek", "kalori": 63 },
    { "nama": "Mangga Harum Manis", "kalori": 46 },
    { "nama": "Mangga Indramayu", "kalori": 72 },
    { "nama": "Mangga Kopek", "kalori": 56 },
    { "nama": "Mangga kwini segar", "kalori": 86 },
    { "nama": "Mangga manalagi segar", "kalori": 133 },
    { "nama": "Mangga Muda", "kalori": 59 },
    { "nama": "Mangga segar", "kalori": 52 },
    { "nama": "Manggis", "kalori": 63 },
    { "nama": "Margarin", "kalori": 720 },
    { "nama": "Markisa segar", "kalori": 144 },
    { "nama": "Markisa squash", "kalori": 217 },
    { "nama": "Martabak manis", "kalori": 265.3 },
    { "nama": "Martabak india", "kalori": 153 },
    { "nama": "Martabak mesir", "kalori": 278 },
    { "nama": "Martabak Telur", "kalori": 200 },
    { "nama": "Masekat", "kalori": 369 },
    { "nama": "Matoa segar", "kalori": 90 },
    { "nama": "Melase", "kalori": 276 },
    { "nama": "Melinjo", "kalori": 66 },
    { "nama": "Melon segar", "kalori": 37 },
    { "nama": "Menjangan daging dendeng mentah", "kalori": 322 },
    { "nama": "Mentega", "kalori": 725 },
    { "nama": "Menteng", "kalori": 65 },
    { "nama": "Merica", "kalori": 359 },
    { "nama": "Mi basah", "kalori": 88 },
    { "nama": "Mi golosor", "kalori": 71 },
    { "nama": "Mi kering", "kalori": 339 },
    { "nama": "Mie aceh rebus", "kalori": 113 },
    { "nama": "Mie ayam", "kalori": 102 },
    { "nama": "Mie bakso", "kalori": 114 },
    { "nama": "Mie basah", "kalori": 86 },
    { "nama": "Mie Bendo", "kalori": 353 },
    { "nama": "Mie celon", "kalori": 102 },
    { "nama": "Mie Goreng", "kalori": 468 },
    { "nama": "Mie kering", "kalori": 337 },
    { "nama": "Mie pangsit basah", "kalori": 105 },
    { "nama": "Mie Sagu", "kalori": 190 },
    { "nama": "Minyak Ikan", "kalori": 902 },
    { "nama": "Minyak Kacang Tanah", "kalori": 902 },
    { "nama": "Minyak kedelai", "kalori": 883 },
    { "nama": "Minyak Kelapa", "kalori": 870 },
    { "nama": "Minyak Kelapa Sawit", "kalori": 902 },
    { "nama": "Minyak Wijen", "kalori": 902 },
    { "nama": "Minyak Zaitun", "kalori": 884 },
    { "nama": "Misoa", "kalori": 345 },
    { "nama": "Misro", "kalori": 218 },
    { "nama": "Moon tahu", "kalori": 128 },
    { "nama": "Mostarda metan -sawi", "kalori": 33 },
    { "nama": "Mujahir acar kuning masakan", "kalori": 330 },
    { "nama": "Naan maran sapi masakan", "kalori": 478 },
    { "nama": "Nanas", "kalori": 52 },
    { "nama": "Nanas palembang segar", "kalori": 58 },
    { "nama": "Nangka biji", "kalori": 165 },
    { "nama": "Nangka masak di pohon", "kalori": 106 },
    { "nama": "Nangka Muda", "kalori": 51 },
    { "nama": "Nasi", "kalori": 180 },
    { "nama": "Nasi beras merah", "kalori": 149 },
    { "nama": "Nasi gemuk", "kalori": 192 },
    { "nama": "Nasi Goreng", "kalori": 276 },
    { "nama": "Nasi gurih", "kalori": 190 },
    { "nama": "Nasi jagung", "kalori": 357 },
    { "nama": "Nasi minyak", "kalori": 207 },
    { "nama": "Nasi rames", "kalori": 155 },
    { "nama": "Nasi tim", "kalori": 120 },
    { "nama": "Nasi Uduk", "kalori": 253.3 },
    { "nama": "Nasu likku masakan", "kalori": 196 },
    { "nama": "Noga Kacang Tanah", "kalori": 600 },
    { "nama": "Nopia spesial", "kalori": 387 },
    { "nama": "Olah-olah", "kalori": 9 },
    { "nama": "Oncom", "kalori": 187 },
    { "nama": "Oncom ampas kacang hijau", "kalori": 376 },
    { "nama": "Oncom Goreng", "kalori": 363.3 },
    { "nama": "Oncom Hitam Goreng", "kalori": 284 },
    { "nama": "Oncom Hitam Goreng bertepung", "kalori": 306.7 },
    { "nama": "Oncom kacang hijau + singkong", "kalori": 351 },
    { "nama": "Oncom Kacang Tanah pepes", "kalori": 297 },
    { "nama": "Oncom Kedele", "kalori": 187 },
    { "nama": "Oncom Merah Goreng", "kalori": 368 },
    { "nama": "Oncom Merah Goreng bertepung", "kalori": 320 },
    { "nama": "Oncom Merah Sayur (tumis)", "kalori": 40 },
    { "nama": "Oncom pepes", "kalori": 76 },
    { "nama": "Onde-onde", "kalori": 288.6 },
    { "nama": "Ongol-ongol", "kalori": 115 },
    { "nama": "Ongol-ongol sagu", "kalori": 111 },
    { "nama": "Opak Singkong", "kalori": 940 },
    { "nama": "Oramu ninahu ndawa olaho masakan", "kalori": 117 },
    { "nama": "Otak", "kalori": 125 },
    { "nama": "Oyek", "kalori": 351 },
    { "nama": "Oyek (dari singkong)", "kalori": 342 },
    { "nama": "Paku hinela wulelenggapaya", "kalori": 77 },
    { "nama": "Pala biji", "kalori": 494 },
    { "nama": "Pala daging", "kalori": 42 },
    { "nama": "Paniki masak santan masakan", "kalori": 460 },
    { "nama": "Papais", "kalori": 133.8 },
    { "nama": "Papeda", "kalori": 61 },
    { "nama": "Parede baleh masakan", "kalori": 87 },
    { "nama": "Paria (Pare)", "kalori": 29 },
    { "nama": "Paria Putih kukus", "kalori": 16 },
    { "nama": "Paria putih segar", "kalori": 19 },
    { "nama": "Pastel", "kalori": 307 },
    { "nama": "Pati Singkong (tapioka)", "kalori": 362 },
    { "nama": "Pe-Cay", "kalori": 23 },
    { "nama": "Peda Ikan Banjar", "kalori": 156 },
    { "nama": "Pelecing kangkung", "kalori": 75 },
    { "nama": "Pelepah manuk masakan", "kalori": 219 },
    { "nama": "Pempek adaan", "kalori": 162 },
    { "nama": "Pempek belida", "kalori": 156 },
    { "nama": "Pempek kapal selam", "kalori": 152 },
    { "nama": "Pempek kelesan", "kalori": 211 },
    { "nama": "Pempek kulit", "kalori": 243 },
    { "nama": "Pempek tenggiri", "kalori": 173 },
    { "nama": "Pencok lele masakan", "kalori": 372 },
    { "nama": "Penyu serapah masakan", "kalori": 174 },
    { "nama": "Pepare ular segar", "kalori": 19 },
    { "nama": "Pepaya lodeh", "kalori": 275 },
    { "nama": "Pepaya Muda", "kalori": 26 },
    { "nama": "Pepaya segar", "kalori": 46 },
    { "nama": "Pepea oncom ampas tahu", "kalori": 76 },
    { "nama": "Permen", "kalori": 400 },
    { "nama": "Pete Segar", "kalori": 142 },
    { "nama": "Peterseli", "kalori": 50 },
    { "nama": "Petis Ikan", "kalori": 161 },
    { "nama": "Petis Udang", "kalori": 220 },
    { "nama": "Petis udang kering", "kalori": 345 },
    { "nama": "Petis udang pasta", "kalori": 220 },
    { "nama": "Pilus", "kalori": 514 },
    { "nama": "Pinda masakan", "kalori": 107 },
    { "nama": "Pindang Ikan Banjar", "kalori": 157 },
    { "nama": "Pindang Ikan Benggol", "kalori": 170 },
    { "nama": "Pindang Ikan Layang", "kalori": 153 },
    { "nama": "Pindang Ikan Selar Kecil", "kalori": 142 },
    { "nama": "Pindang kenari masakan", "kalori": 124 },
    { "nama": "Pisang Ambon", "kalori": 99 },
    { "nama": "Pisang angleng (pisang ampyang) segar", "kalori": 68 },
    { "nama": "Pisang ayam segar", "kalori": 120 },
    { "nama": "Pisang gapi segar", "kalori": 127 },
    { "nama": "Pisang Goreng", "kalori": 220 },
    { "nama": "Pisang goroho segar", "kalori": 115 },
    { "nama": "Pisang hijau segar", "kalori": 117 },
    { "nama": "Pisang kayu segar", "kalori": 100 },
    { "nama": "Pisang kepok segar", "kalori": 109 },
    { "nama": "Pisang ketip segar", "kalori": 145 },
    { "nama": "Pisang kidang segar", "kalori": 96 },
    { "nama": "Pisang Lampung", "kalori": 99 },
    { "nama": "Pisang Mas", "kalori": 127 },
    { "nama": "Pisang mas bali", "kalori": 127 },
    { "nama": "Pisang Oli", "kalori": 134 },
    { "nama": "Pisang Raja", "kalori": 120 },
    { "nama": "Pisang Raja Sere (Susu)", "kalori": 118 },
    { "nama": "Pisang rotan segar", "kalori": 98 },
    { "nama": "Pisang Siam goreng", "kalori": 625 },
    { "nama": "Pisang talas segar", "kalori": 113 },
    { "nama": "Prey (bawang daun)", "kalori": 45 },
    { "nama": "Pucuk lumai/daun leunca segar", "kalori": 33 },
    { "nama": "Pulut", "kalori": 216 },
    { "nama": "Punai daging goreng", "kalori": 224 },
    { "nama": "Pundut nasi", "kalori": 104 },
    { "nama": "Purundawa", "kalori": 25 },
    { "nama": "Purut segar", "kalori": 76 },
    { "nama": "Putri malu segar", "kalori": 76 },
    { "nama": "Putri selat", "kalori": 163 },
    { "nama": "Putu Mayang", "kalori": 200 },
    { "nama": "Ragi", "kalori": 136 },
    { "nama": "Rajungan segar", "kalori": 76 },
    { "nama": "Rambutan", "kalori": 69 },
    { "nama": "Rambutan Aceh", "kalori": 11 },
    { "nama": "Rambutan binjai segar", "kalori": 76 },
    { "nama": "Rambutan sinyonya", "kalori": 4 },
    { "nama": "Rarawuan", "kalori": 295 },
    { "nama": "Rasbi (Beras Ubi)", "kalori": 394 },
    { "nama": "Rasi (Beras Singkong)", "kalori": 350 },
    { "nama": "Rawon masakan", "kalori": 60 },
    { "nama": "Rebon (udang kecil segar)", "kalori": 81 },
    { "nama": "Rebon kering", "kalori": 299 },
    { "nama": "Rebon udang kecil segar", "kalori": 81 },
    { "nama": "Rebung", "kalori": 27 },
    { "nama": "Rebung laut mentah", "kalori": 320 },
    { "nama": "Rempeyek kacang tolo", "kalori": 451 },
    { "nama": "Rempeyek kacang uci", "kalori": 497 },
    { "nama": "Rendang sapi masakan", "kalori": 193 },
    { "nama": "Renggi goreng", "kalori": 471 },
    { "nama": "Rimbang segar", "kalori": 75 },
    { "nama": "Risoles", "kalori": 335 },
    { "nama": "Roti boong", "kalori": 341 },
    { "nama": "Roti Gambang", "kalori": 350 },
    { "nama": "Roti Putih", "kalori": 248 },
    { "nama": "Roti warna sawo matang", "kalori": 249 },
    { "nama": "Rujak cingur", "kalori": 153 },
    { "nama": "Rumput laut", "kalori": 41 },
    { "nama": "Rusa daging dendeng mentah", "kalori": 536 },
    { "nama": "Rusip", "kalori": 110 },
    { "nama": "RW anjing masakan", "kalori": 198 },
    { "nama": "Saga biji tanpa kulit", "kalori": 449 },
    { "nama": "Sagu Ambon", "kalori": 338 },
    { "nama": "Sagu aren kering", "kalori": 355 },
    { "nama": "Sagu aren segar", "kalori": 231 },
    { "nama": "Sagu forno", "kalori": 291 },
    { "nama": "Sagu kasbi segar", "kalori": 230 },
    { "nama": "Sagu Lemak (Kue Sagon)", "kalori": 452 },
    { "nama": "Sagu lempeng", "kalori": 347 },
    { "nama": "Sagu Rendang", "kalori": 364 },
    { "nama": "Sagu singkong kering", "kalori": 362 },
    { "nama": "Sagu sinole", "kalori": 354 },
    { "nama": "Salak bali segar", "kalori": 57 },
    { "nama": "Salak medan segar", "kalori": 55 },
    { "nama": "Salak pondoh segar", "kalori": 87 },
    { "nama": "Sale pisang siam", "kalori": 281 },
    { "nama": "Santan (dengan air)", "kalori": 122 },
    { "nama": "Santan (kelapa saja)", "kalori": 324 },
    { "nama": "Santan murni", "kalori": 324 },
    { "nama": "Saos Tomat", "kalori": 98 },
    { "nama": "Sapi abon", "kalori": 212 },
    { "nama": "Sapi babat segar", "kalori": 108 },
    { "nama": "Sapi daging asap", "kalori": 182 },
    { "nama": "Sapi daging dendeng mentah", "kalori": 301 },
    { "nama": "Sapi daging gemuk segar", "kalori": 273 },
    { "nama": "Sapi daging kornet", "kalori": 289 },
    { "nama": "Sapi daging kurus segar", "kalori": 174 },
    { "nama": "Sapi daging lemak sedang segar", "kalori": 201 },
    { "nama": "Sapi daging sosis (Worst)", "kalori": 448 },
    { "nama": "Sapi daleman segar", "kalori": 183 },
    { "nama": "Sapi dideh/darah", "kalori": 98 },
    { "nama": "Sapi ginjal segar", "kalori": 137 },
    { "nama": "Sapi hati sosis (liverworst)", "kalori": 274 },
    { "nama": "Sapi keleponan segar", "kalori": 84 },
    { "nama": "Sapi liver segar", "kalori": 132 },
    { "nama": "Sapi otak segar", "kalori": 123 },
    { "nama": "Sapi paru dendeng mentah", "kalori": 360 },
    { "nama": "Sapi paru goreng", "kalori": 268 },
    { "nama": "Sapi usus segar", "kalori": 126 },
    { "nama": "Sarang Burung", "kalori": 281 },
    { "nama": "Sardines dalam kaleng", "kalori": 338 },
    { "nama": "Sari Kedelai bubuk", "kalori": 344 },
    { "nama": "Sarimuka", "kalori": 166 },
    { "nama": "Sate Bandeng", "kalori": 283 },
    { "nama": "Sate Kulit", "kalori": 110 },
    { "nama": "Sate penyu masakan", "kalori": 179 },
    { "nama": "Sate pusut masakan", "kalori": 274 },
    { "nama": "Sate Usus", "kalori": 126.7 },
    { "nama": "Sawi", "kalori": 22 },
    { "nama": "Sawi putih / pecai segar", "kalori": 9 },
    { "nama": "Sawi taiwan segar", "kalori": 30 },
    { "nama": "Sawi tanah segar", "kalori": 19 },
    { "nama": "Sawo", "kalori": 92 },
    { "nama": "Sawo duren segar", "kalori": 64 },
    { "nama": "Sawo kecik segar", "kalori": 111 },
    { "nama": "Sawo Manila segar", "kalori": 92 },
    { "nama": "Sayur asem", "kalori": 29 },
    { "nama": "Sayur bunga pepaya", "kalori": 49 },
    { "nama": "Sayur garu", "kalori": 178 },
    { "nama": "Sayur kohu-kohu", "kalori": 133 },
    { "nama": "Sayur lebui", "kalori": 64 },
    { "nama": "Sayur lilin-terubuk", "kalori": 36 },
    { "nama": "Sayur ndusuk", "kalori": 49 },
    { "nama": "Sayur sop", "kalori": 27 },
    { "nama": "Sayur umbut kelapa", "kalori": 67 },
    { "nama": "Sayur umbut rotan", "kalori": 57 },
    { "nama": "Selada", "kalori": 15 },
    { "nama": "Selada Air", "kalori": 17 },
    { "nama": "Selada Air rebus", "kalori": 19 },
    { "nama": "Seledri", "kalori": 20 },
    { "nama": "Semangka", "kalori": 28 },
    { "nama": "Semur Jengkol", "kalori": 192.5 },
    { "nama": "Sente", "kalori": 64 },
    { "nama": "Sente talas segar", "kalori": 353 },
    { "nama": "Sepi masakan", "kalori": 88 },
    { "nama": "Serbuk Coklat", "kalori": 298 },
    { "nama": "Serimping talas kebumen", "kalori": 478 },
    { "nama": "Setrup sirup", "kalori": 213 },
    { "nama": "Shabu-shabu", "kalori": 88 },
    { "nama": "Sie reuboh masakan", "kalori": 474 },
    { "nama": "Singkah (rotan muda)", "kalori": 81 },
    { "nama": "Singkong Goreng", "kalori": 285 },
    { "nama": "Singkong kukus", "kalori": 146 },
    { "nama": "Singkong tape", "kalori": 173 },
    { "nama": "Siomay", "kalori": 95.3 },
    { "nama": "Sirsak", "kalori": 65 },
    { "nama": "Sirup", "kalori": 213 },
    { "nama": "Sop buntut masakan", "kalori": 71 },
    { "nama": "Sop daging sapi masakan", "kalori": 49 },
    { "nama": "Sop kaki sapi masakan", "kalori": 68 },
    { "nama": "Sop kambing masakan", "kalori": 34 },
    { "nama": "Sop konro masakan", "kalori": 71 },
    { "nama": "Sop Kool", "kalori": 12 },
    { "nama": "Sop Kool dan Wortel", "kalori": 15 },
    { "nama": "Sop saudara masakan", "kalori": 89 },
    { "nama": "Soto bandung masakan", "kalori": 42 },
    { "nama": "Soto banjar masakan", "kalori": 110 },
    { "nama": "Soto betawi masakan", "kalori": 135 },
    { "nama": "Soto dengan Daging", "kalori": 127.5 },
    { "nama": "Soto jeroan masakan", "kalori": 92 },
    { "nama": "Soto kudus masakan", "kalori": 38 },
    { "nama": "Soto madura masakan", "kalori": 60 },
    { "nama": "Soto padang masakan", "kalori": 127 },
    { "nama": "Soto pekalongan masakan", "kalori": 94 },
    { "nama": "Soto pemalang masakan", "kalori": 75 },
    { "nama": "Soto sukaraja masakan", "kalori": 80 },
    { "nama": "Soto sulung masakan", "kalori": 86 },
    { "nama": "Soto tanpa Daging", "kalori": 117.1 },
    { "nama": "Spaghetti", "kalori": 139 },
    { "nama": "Srikaya", "kalori": 101 },
    { "nama": "Sukiyaki masakan", "kalori": 75 },
    { "nama": "Sukun muda segar", "kalori": 119 },
    { "nama": "Sukun tua segar", "kalori": 126 },
    { "nama": "Susu asam untuk bayi bubuk", "kalori": 418 },
    { "nama": "Susu bubuk", "kalori": 513 },
    { "nama": "Susu Kambing", "kalori": 64 },
    { "nama": "Susu Kedelai", "kalori": 41 },
    { "nama": "Susu Kental Manis", "kalori": 336 },
    { "nama": "Susu Kental Tak Manis", "kalori": 138 },
    { "nama": "Susu Kerbau", "kalori": 160 },
    { "nama": "Susu Sapi", "kalori": 61 },
    { "nama": "Susu Skim (tak berlemak)", "kalori": 36 },
    { "nama": "Susu skim bubuk", "kalori": 359 },
    { "nama": "Susu skim segar", "kalori": 36 },
    { "nama": "Susupan", "kalori": 87 },
    { "nama": "Suweg kukus", "kalori": 90 },
    { "nama": "Suweg mentah", "kalori": 69 },
    { "nama": "Suweg talas segar", "kalori": 74 },
    { "nama": "Suwir-suwir", "kalori": 347 },
    { "nama": "Tahu", "kalori": 68 },
    { "nama": "Tahu goreng", "kalori": 115 },
    { "nama": "Tahu telur", "kalori": 328 },
    { "nama": "Takwa", "kalori": 148 },
    { "nama": "Talas bogor kukus", "kalori": 120 },
    { "nama": "Talas pontianak segar", "kalori": 163 },
    { "nama": "Talas viqueque segar", "kalori": 115 },
    { "nama": "Tales kukus", "kalori": 120 },
    { "nama": "Tales mentah", "kalori": 98 },
    { "nama": "Taoco", "kalori": 166 },
    { "nama": "Taoge goreng", "kalori": 88 },
    { "nama": "Taoge kacang kedelai segar", "kalori": 76 },
    { "nama": "Taoge seduh", "kalori": 28 },
    { "nama": "Taoge segar", "kalori": 34 },
    { "nama": "Taokoa", "kalori": 104 },
    { "nama": "Tapai beras", "kalori": 99 },
    { "nama": "Tapai ketan hitam", "kalori": 166 },
    { "nama": "Tapai ketan putih", "kalori": 172 },
    { "nama": "Tapai singkong", "kalori": 169 },
    { "nama": "Tauco cap DAS cake", "kalori": 358 },
    { "nama": "Tauji cap singa", "kalori": 277 },
    { "nama": "Tebu Terubuk", "kalori": 25 },
    { "nama": "Tedong pallu basa masakan", "kalori": 83 },
    { "nama": "Teh", "kalori": 132 },
    { "nama": "Teh hijau daun kering", "kalori": 300 },
    { "nama": "Teh melati daun kering", "kalori": 299 },
    { "nama": "Tekokak", "kalori": 34 },
    { "nama": "Tekokak kering", "kalori": 294 },
    { "nama": "Tekwan", "kalori": 53 },
    { "nama": "Telur Ayam", "kalori": 162 },
    { "nama": "Telur Ayam bagian kuning", "kalori": 361 },
    { "nama": "Telur Ayam bagian putih", "kalori": 50 },
    { "nama": "Telur Ayam ceplok", "kalori": 383 },
    { "nama": "Telur Ayam dadar", "kalori": 251 },
    { "nama": "Telur ayam kampung", "kalori": 179 },
    { "nama": "Telur bebek bagian kuning segar", "kalori": 386 },
    { "nama": "Telur Bebek bagian putih", "kalori": 54 },
    { "nama": "Telur bebek bagian putih segar", "kalori": 54 },
    { "nama": "Telur Bebek ceplok", "kalori": 320 },
    { "nama": "Telur Bebek dadar", "kalori": 301 },
    { "nama": "Telur bebek tambak segar", "kalori": 187 },
    { "nama": "Telur Bebek telur asin", "kalori": 195 },
    { "nama": "Telur burung puyuh segar", "kalori": 116 },
    { "nama": "Telur Penyu", "kalori": 144 },
    { "nama": "Telur Terubuk", "kalori": 425 },
    { "nama": "Tempe bongkrek", "kalori": 119 },
    { "nama": "Tempe Gembus", "kalori": 73 },
    { "nama": "Tempe gembus yogya", "kalori": 76 },
    { "nama": "Tempe Goreng", "kalori": 328 },
    { "nama": "Tempe kacang babi", "kalori": 139 },
    { "nama": "Tempe kacang belimbing", "kalori": 212 },
    { "nama": "Tempe kedelai + jagung", "kalori": 143 },
    { "nama": "Tempe kedelai murni goreng", "kalori": 350 },
    { "nama": "Tempe kedelai murni mentah", "kalori": 201 },
    { "nama": "Tempe koro benguk", "kalori": 141 },
    { "nama": "Tempe lamtoro var. gung dengan kulit", "kalori": 146 },
    { "nama": "Tempe lamtoro var. gung tanpa kulit", "kalori": 131 },
    { "nama": "Tempe pasar segar", "kalori": 150 },
    { "nama": "Tempe pasar goreng", "kalori": 336 },
    { "nama": "Tempe Sayur", "kalori": 240 },
    { "nama": "Tempoya", "kalori": 110 },
    { "nama": "Tempuyak", "kalori": 126 },
    { "nama": "Tepung Arrowroot", "kalori": 355 },
    { "nama": "Tepung Beras", "kalori": 364 },
    { "nama": "Tepung beras mentah", "kalori": 353 },
    { "nama": "Tepung Ganyong", "kalori": 353 },
    { "nama": "Tepung Gaplek", "kalori": 363 },
    { "nama": "Tepung Garut (arrowroot)", "kalori": 355 },
    { "nama": "Tepung Hunkwee", "kalori": 364 },
    { "nama": "Tepung Ikan", "kalori": 316 },
    { "nama": "Tepung Jagung Kuning", "kalori": 355 },
    { "nama": "Tepung jagung putih", "kalori": 355 },
    { "nama": "Tepung Jalejo", "kalori": 388 },
    { "nama": "Tepung Kacang Kedelai", "kalori": 347 },
    { "nama": "Tepung Kentang", "kalori": 347 },
    { "nama": "Tepung Mocaf", "kalori": 350 },
    { "nama": "Tepung Pisang", "kalori": 338 },
    { "nama": "Tepung Sagu", "kalori": 353 },
    { "nama": "Tepung Sente", "kalori": 326 },
    { "nama": "Tepung singkong/ Tapioka", "kalori": 363 },
    { "nama": "Tepung Sukun", "kalori": 353 },
    { "nama": "Tepung Susu", "kalori": 509 },
    { "nama": "Tepung Susu Asam untuk bayi", "kalori": 418 },
    { "nama": "Tepung Susu Skim", "kalori": 362 },
    { "nama": "Tepung Tales Beneng", "kalori": 332 },
    { "nama": "Tepung Terigu", "kalori": 365 },
    { "nama": "Tepung Ubi Ungu", "kalori": 354 },
    { "nama": "Terasi", "kalori": 155 },
    { "nama": "Terasi dobo", "kalori": 191 },
    { "nama": "Terasi Merah", "kalori": 174 },
    { "nama": "Terasi merah", "kalori": 174 },
    { "nama": "Teri balado masakan", "kalori": 365 },
    { "nama": "Teripang dendeng mentah", "kalori": 462 },
    { "nama": "Terong", "kalori": 24 },
    { "nama": "Terong + Oncom makanan", "kalori": 285 },
    { "nama": "Terong Asam", "kalori": 39 },
    { "nama": "Terong Belanda", "kalori": 48 },
    { "nama": "Terong hintalo segar", "kalori": 45 },
    { "nama": "Terong kukus", "kalori": 23 },
    { "nama": "Terong segar", "kalori": 28 },
    { "nama": "Terung belanda segar", "kalori": 52 },
    { "nama": "Terung bengkulu segar", "kalori": 52 },
    { "nama": "Terung panjang", "kalori": 25 },
    { "nama": "Terung panjang kukus", "kalori": 23 },
    { "nama": "Tespong daun", "kalori": 59 },
    { "nama": "Tim (nasi tim)", "kalori": 120 },
    { "nama": "Tinira ninahu nggaluku", "kalori": 33 },
    { "nama": "Tinoransak masakan", "kalori": 516 },
    { "nama": "Tipa-tipa", "kalori": 355 },
    { "nama": "Tiwul", "kalori": 353 },
    { "nama": "Tiwul Instan", "kalori": 395 },
    { "nama": "Toge -Tahu makanan", "kalori": 392 },
    { "nama": "Toge Goreng", "kalori": 93.6 },
    { "nama": "Toge kacang ijo", "kalori": 23 },
    { "nama": "Toge kacang tunggak", "kalori": 35 },
    { "nama": "Toge kedelai", "kalori": 67 },
    { "nama": "Toge seduh", "kalori": 28 },
    { "nama": "Tomat air (juice) segar", "kalori": 20 },
    { "nama": "Tomat Masak", "kalori": 20 },
    { "nama": "Tomat merah segar", "kalori": 24 },
    { "nama": "Tomat muda segar", "kalori": 24 },
    { "nama": "Tumis bandeng", "kalori": 189 },
    { "nama": "Tumis bayam bersantan", "kalori": 48 },
    { "nama": "Ubi Cilembu", "kalori": 186 },
    { "nama": "Ubi Jalar Goreng", "kalori": 160 },
    { "nama": "Ubi jalar kuning kukus", "kalori": 100 },
    { "nama": "Ubi jalar kuning segar", "kalori": 119 },
    { "nama": "Ubi jalar manis segar", "kalori": 83 },
    { "nama": "Ubi Jalar Merah", "kalori": 123 },
    { "nama": "Ubi jalar merah segar", "kalori": 151 },
    { "nama": "Ubi Jalar Putih", "kalori": 123 },
    { "nama": "Ubi Jalar Rebus", "kalori": 114 },
    { "nama": "Ubi Jalar Sayur", "kalori": 184 },
    { "nama": "Ubi jalar tinta/ kemayung", "kalori": 108 },
    { "nama": "Ubi jalar tinta/ kemayung kukus", "kalori": 165 },
    { "nama": "Uceng/ bunga melinjo segar", "kalori": 82 },
    { "nama": "Udang besar segar", "kalori": 56 },
    { "nama": "Udang galah segar", "kalori": 81 },
    { "nama": "Udang kering", "kalori": 295 },
    { "nama": "Udang kering mentah", "kalori": 278 },
    { "nama": "Udang papay mentah", "kalori": 273 },
    { "nama": "Udang segar", "kalori": 91 },
    { "nama": "Ulat sagu panggang", "kalori": 380 },
    { "nama": "Ulat sagu segar", "kalori": 241 },
    { "nama": "Umbi Uwi segar", "kalori": 120 },
    { "nama": "Umbut rotan", "kalori": 34 },
    { "nama": "Usus Sapi", "kalori": 130 },
    { "nama": "Uwi", "kalori": 101 },
    { "nama": "Vermicelli", "kalori": 363 },
    { "nama": "Wajit", "kalori": 303 },
    { "nama": "Waluh balamak", "kalori": 45 },
    { "nama": "Widaran", "kalori": 424 },
    { "nama": "Wijen", "kalori": 568 },
    { "nama": "Wingko babat", "kalori": 355 },
    { "nama": "Woku ubi", "kalori": 143 },
    { "nama": "Sosis daging", "kalori": 452 },
    { "nama": "Wortel Segar", "kalori": 42 },
    { "nama": "Wortel kukus", "kalori": 37 },
    { "nama": "Wortel rebus", "kalori": 28 },
    { "nama": "Yangko", "kalori": 254 },
    { "nama": "Yoghurt", "kalori": 52 }
  ];

  const backgroundStyle = {
    background: 'linear-gradient(to bottom, #FFFFFF 0%, #93DCC8 50%, #F7F1E3 100%)',
  };

  const handleSearchChange = (e) => {
    setSearchTerm(e.target.value.toLowerCase());
  };

  const filteredMenu = rekomendasiMenu.filter((item) =>
    item.nama.toLowerCase().includes(searchTerm)
  );

  const handleItemClick = (item) => {
    navigate(`/detailmenu/${encodeURIComponent(item.nama)}`, { state: { makanan: item } });
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -30 }}
      transition={{ duration: 0.6 }}
      className="fixed inset-0 w-full flex flex-col items-center overflow-y-auto"
      style={backgroundStyle}
    >
      <div className="w-full flex flex-col flex-grow">
        {/* ✅ Navbar */}
        <nav className="w-full bg-[#16A085] text-white py-1 px-4 shadow-md">
          <div className="container mx-auto flex justify-between items-center">
            <img src={logo} alt="Logo ObsiCare" className="h-25 w-auto" />
            <ul className="flex gap-4 text-lg font-medium"></ul>

            {/* Navigation Links */}
            <ul className="flex gap-25 items-center font-bold text-xl tracking-widest text-white">
              <li>
                <NavLink
                  to="/"
                  className={({ isActive }) =>
                    isActive
                      ? "text-white underline underline-offset-4 !text-white"
                      : "text-white hover:text-[#FFFDD0]"
                  }
                >
                  Beranda
                </NavLink>

              </li>
              <li>
                <NavLink
                  to="/about"
                  className={({ isActive }) =>
                    isActive
                      ? "text-white underline underline-offset-4 !text-white"
                      : "text-white hover:text-[#FFFDD0]"
                  }
                >
                  Tentang
                </NavLink>

              </li>
              <li>
                <Link
                  to="/signup"
                  className="bg-teal-200 px-6 py-2 rounded-full !text-[#0F836C] font-poppins hover:bg-teal-300 hover:text-[#FFFDD0]"
                >
                  Daftar
                </Link>
              </li>
              <li>
                <Link
                  to="/signin"
                  className="bg-teal-200 px-6 py-2 rounded-full !text-[#0F836C] font-poppins hover:bg-teal-300 hover:text-[#FFFDD0]"
                >
                  Masuk
                </Link>
              </li>
            </ul>
          </div>
        </nav>

        {/* Logo kiri */}
        <img
          src={logoKiri}
          alt="Logo Kiri"
          className="absolute top-12 left-[14%] w-90 h-90 object-contain z-10"
        />

        {/* Container sisa kalori di sebelah kanan logo kiri */}
        <div className="absolute top-45 left-[68%] z-10">
          <div className="bg-[#E0F5F1]  p-4 rounded-lg shadow border border-[#16A085] w-64 text-center">
            <h3 className="text-xl font-semibold text-gray-700 mb-2">Sisa Kalorimu</h3>
            <p className="text-1.5xl font-medium text-[#16A085]">-- Kkal</p> {/* Ganti dengan state jika dinamis */}
          </div>
        </div>

        {/* Container Menu */}
        <div className="relative z-10 mx-auto mt-48 p-4 bg-[#E0F5F1] rounded-xl shadow-lg w-[100%] max-w-7xl border border-[#16A085] pb-20">
          {/* Search Bar */}
          <div className="flex justify-center mb-10 relative z-50">
            <div className="w-72">
              {/* Input */}
              <div className="flex items-center bg-white px-4 py-2 rounded-full shadow ring-1 ring-gray-300 w-full border" style={{ borderColor: '#16A085' }}>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="w-5 h-5 text-gray-500 mr-2"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M21 21l-4.35-4.35m0 0a7.5 7.5 0 11-10.61-10.61 7.5 7.5 0 0110.61 10.61z"
                  />
                </svg>
                <input
                  type="text"
                  placeholder="Temukan makanan favoritmu"
                  value={searchTerm}
                  onChange={handleSearchChange}
                  className="w-full outline-none bg-transparent placeholder-gray-500"
                />
              </div>

              {/* Dropdown suggestion */}
              {searchTerm && filteredMenu.length > 0 && (
                <ul className="absolute w-72 mt-1 bg-white border border-gray-300 rounded-lg shadow-lg max-h-60 overflow-y-auto z-50">
                  {filteredMenu.slice(0, 10).map((item, idx) => (
                    <li
                      key={idx}
                      className="px-4 py-2 text-sm hover:bg-[#E0F5F1] cursor-pointer truncate"
                      onClick={() => handleItemClick(item)}
                    >
                      {item.nama}
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </div>

          {/* Daftar Menu */}
          <div className="max-h-[200px] overflow-y-auto pr-2">
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
              {filteredMenu.length > 0 ? (
                filteredMenu.map((item, idx) => (
                  <div
                    key={idx}
                    className="bg-[#F0F9F5] rounded-lg p-4 text-center shadow hover:shadow-md transition"
                  >
                    <p className="font-medium">{item.nama}</p>
                    <p className="text-sm text-gray-600">{item.kalori} Kkal</p>
                  </div>
                ))
              ) : (
                <p className="text-center col-span-4 text-gray-600">Tidak ada data ditemukan.</p>
              )}
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
};

export default Menu;